services:
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:v1.0.0
    ports:
    - 8101:8025
    - 1025:1025
  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    image: dpage/pgadmin4:4.18
    links:
    - postgres_database:pgsql-server
    ports:
    - 8100:80
    restart: always
    volumes:
    - pgadmin_data:/var/lib/pgadmin/
  postgres_database:
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=postgres_database
    image: postgres:12.0-alpine
    ports:
    - 5432:5432
    restart: always
    volumes:
    - postgres_data:/var/lib/postgresql/data/
  service_accounts:
    build:
      context: ./service_accounts
      dockerfile: ./docker/Dockerfile
    command: python ./src/manage.py runserver 0.0.0.0:8000
    container_name: service_accounts
    depends_on:
    - postgres_database
    env_file:
    - service_accounts/environments/.development.env
    image: service_accounts
    ports:
    - 8001:8000
    restart: always
    volumes:
    - ./service_accounts/:/usr/src/app/
  service_frontend:
    build:
      context: ./service_frontend
      dockerfile: ./docker/Dockerfile
    command: npm start
    container_name: service_frontend
    depends_on:
    - postgres_database
    env_file:
    - service_frontend/environments/.development.env
    image: service_frontend
    ports:
    - 8000:3000
    restart: always
    volumes:
    - ./service_frontend/:/usr/src/app/
  service_test:
    build:
      context: ./service_test
      dockerfile: ./docker/Dockerfile
    command: python ./src/manage.py runserver 0.0.0.0:8000
    container_name: service_test
    depends_on:
    - service_test_database
    env_file:
    - service_test/environments/.development.env
    image: service_test
    ports:
    - 8002:8000
    restart: always
    volumes:
    - ./service_test/:/usr/src/app/
  service_test_database:
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=service_test_database
    image: postgres:12.0-alpine
    ports:
    - 5433:5432
    restart: always
    volumes:
    - service_test_database_data:/var/lib/postgresql/data/
version: '3.7'
volumes:
  pgadmin_data: null
  postgres_data: null
  service_test_database_data: null
