port_registry:
  mailhog_backend: 1025
  mailhog_frontend: 8101
  pgadmin: 8100
  postgres_database: 5432
  service_accounts: 8001
  service_frontend: 8000
  databases:
    - 5432
  services:
  - 8000
  - 8001
protocol: http://
services:
- service_frontend
- service_accounts
site_name: site_name
