# Generated by Django 3.2.9 on 2021-12-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_applications", "0002_auto_20211221_1150"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userownedapplications",
            old_name="active",
            new_name="owned",
        ),
        migrations.AddField(
            model_name="marketplaceapplications",
            name="description",
            field=models.TextField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userownedapplications",
            name="duration",
            field=models.DurationField(null=True),
        ),
    ]
