# Generated by Django 3.2.9 on 2021-12-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_applications", "0003_auto_20211221_1326"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userownedapplications",
            name="duration",
        ),
        migrations.AddField(
            model_name="userownedapplications",
            name="valid_to",
            field=models.DateTimeField(null=True),
        ),
    ]
