# Generated by Django 3.2.9 on 2021-12-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_applications", "0004_auto_20211221_1331"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceapplications",
            name="url",
            field=models.CharField(default="", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="marketplaceapplications",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userownedapplications",
            name="activation_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userownedapplications",
            name="valid_to",
            field=models.DateField(null=True),
        ),
    ]
