# Generated by Django 3.2.9 on 2021-12-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_applications', '0006_marketplaceapplications_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userownedapplications',
            old_name='valid_to',
            new_name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='userownedapplications',
            name='owned',
        ),
    ]
