# Generated by Django 3.2.9 on 2021-12-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_applications', '0007_auto_20211223_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceapplications',
            name='url',
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
