services:
  backend_accounts:
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
    image: backend_accounts_service
    container_name: backend_accounts
    command: python ./src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8001"
    env_file:
      - .env

    postgres_database:
      image: postgres:12.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=postgres_db_dev
