port_registry:
  mailhog_backend: 1025
  mailhog_frontend: 8011
  pgadmin: 8010
  postgres_database: 5432
  service_accounts: 8001
  service_frontend: 8000
  services:
  - 8000
  - 8001
protocol: http://
services:
- service_frontend
- service_accounts
- service_test
- service_test2
- service_test
site_name: site_name
