on:
  push:
  pull_request:
    branches:
      - main
      - dev

jobs:
  accounts_service_testing:
    runs-on: ubuntu-latest
    name: Unit tests for the accounts
    environment: develop
    env:
      COMPOSE_FILE: ./accounts/.CI/docker-compose.yml
    steps:
      - name: check out codebase
        uses: actions/checkout@v2

      - name: Build docker container
        run: |
          touch ./accounts/.CI/.env
          cd ./accounts/.CI
          ls
          echo ${{ secret.test }}