on:
  push:
  pull_request:
    branches:
      - main
      - dev

jobs:
  accounts_service_testing:
    runs-on: ubuntu-latest
    name: Unit tests for the accounts service
    env:
      COMPOSE_FILE: .ci/docker-compose.yml
    steps:
      - name: check out codebase
        uses: actions/checkout@v2

      - name: Build docker container
        run: |
          echo ls
          touch ./accounts/.CI/.env
          cd ./accounts/.CI
          echo ls