on:
  push:
  pull_request:
    branches:
      - main
      - dev

jobs:
  accounts_service_testing:
    runs-on: ubuntu-latest
    name: Unit tests for the accounts
    env:
      COMPOSE_FILE: ./accounts/.CI/docker-compose.yml
    steps:
      - name: check out codebase
        uses: actions/checkout@v2

      - name: Build docker container
        run: |
          touch ./accounts/.CI/.env
          echo TEST=${{ secrets.TEST2 }} >> ./accounts/.CI/.env
          cat ./accounts/.CI/.env