name: continous integration
on:
  push:
    branches:
      - main
      - dev
jobs:
  linting:
    - name: eslint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
        - run: npm install
          working-directory: ./service_frontend/
        - run: npm run eslint
          working-directory: ./service_frontend/
