# CI/CD to run tests on commit
on:
 push:
  branches:
   - main
   - dev
  paths-ignore: '**.md'
 pull_request:
  branches:
   - main
   - dev
  paths-ignore: '**.md'

jobs:
 frontend-service-tests:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - run: cd frontend
   - uses: actions/setup-node@v2
   - run: npm ci
   - run: npm test