name: service_test
on:
  push:
  pull_request:
    branches:
      - main
      - dev

jobs:
  service_accounts_testing:
    environment: develop
    name: Unit tests for service_test
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: ls
