name: service_accounts_tests

on:
  push:
  pull_request:
    branches:
      - main
      - dev

jobs:
  accounts_service_testing:
    runs-on: ubuntu-latest
    name: Unit tests for the accounts
    environment: develop

    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER:  admin
          POSTGRES_DB: postgres_db_dev
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - '5432:5432'

    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Setup cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r service_accounts/requirements/requirements.txt
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Create migrations and run tests
        env:
          DJANGO_ALLOWED_HOSTS:  ${{ secrets.DJANGO_ALLOWED_HOSTS }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SQL_PASSWORD: admin
          SQL_USER: admin
          SQL_DATABASE: postgres_db_dev
          FRONTEND_URL: 'localhost:8000'
          DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
        run: |
          python service_accounts/src/manage.py makemigrations users
          python service_accounts/src/manage.py migrate
          python service_accounts/src/manage.py test users/test